### ISSUE TITLE
min width and closing taps.

### ISSUE THREAD

**Issue by Athax** [brimelow/Response-for-Brackets#69]
Hi when u have made a media quary the coloured taps on top, can u cancel them? also is it possible to make min-widths also instead of max-widths?

**Comment by ikbenben** [comment]
@Athax . for your first question, there is already two issues open to 'manage' the media queries at the top of the preview pane. See #64 and #65. For now, you can work around it by closing responsive mode,  remove the media query from the css file directly and then reopen responsive mode. I'm planning on working on this in 0.0.8 milestone. We are currently working on 0.0.7

For the second question, I was thinking the same thing but I'm trying to get a stable 1.0 version out before we tackle min-width. Will need to think about how this will work from a usability stand point. I've now created issue #70 so that it is not forgotten

If you are satisfied with response, then please close this issue
